### ISSUE TITLE
use in array formItem name

### ISSUE THREAD

**Issue by masoud-Tesna** [MrBr/antd-zod#5]
hi,
In my form, it is called array

<Form.Item
          name={ [ 'config', 'type' ] }
          label={ 'Authentication type' }
          rules={ [ createSchemaFieldRule(ProviderAuthZod) ] }
        >
          <Select
            options={ [
              {
                label: 'Custom',
                value: 'Custom'
              },
              {
                label: 'OAuth',
                value: 'OAuth'
              }
            ] }
          />
        </Form.Item>
        
in this case dont work

**Comment by MrBr** [comment]
Hey, sorry for a late reply. It should be working, I've added an example https://github.com/MrBr/antd-zod/blob/main/stories/basic.stories.tsx#L29

**Comment by masoud-Tesna** [comment]
> Hey, sorry for a late reply. It should be working, I've added an example https://github.com/MrBr/antd-zod/blob/main/stories/basic.stories.tsx#L29

I mean this when the name of the form item is like this: name={ [ 'config', 'type' ] }

**Comment by MrBr** [comment]
Added a story for nested property. It should be working. Please double check you're Zod schema.

https://github.com/MrBr/antd-zod/blob/main/stories/basic.stories.tsx#L42
