### ISSUE TITLE
Compatible with antd component

### ISSUE THREAD

**Issue by sia-fl** [MrBr/antd-zod#9]
[antd pro components](https://procomponents.ant.design/en-US/components/editable-table)

When this table component is added or modified, the field name obtained inside the component is in the format of `${key}.${field}`. For example, there is a piece of data called `{id: 123, name: 'qwe'} `, then when the name changes, the obtained field name is `123.name`

[codesandbox](https://codesandbox.io/p/sandbox/beautiful-kare-z6vd5v?file=%2FApp.tsx%3A93%2C18&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltmdxyg000063j6jwbv8ri8c%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltmdxyg000023j6jbja5vp3s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltmdxyg000033j6jnt6fvu7p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltmdxyg000053j6joq56rcy2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltmdxyg000023j6jbja5vp3s%2522%253A%257B%2522id%2522%253A%2522cltmdxyg000023j6jbja5vp3s%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltmeauie00023j6icn9kvat4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A93%252C%2522startColumn%2522%253A18%252C%2522endLineNumber%2522%253A93%252C%2522endColumn%2522%253A18%257D%255D%252C%2522filepath%2522%253A%2522%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltmeauie00023j6icn9kvat4%2522%257D%252C%2522cltmdxyg000053j6joq56rcy2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltmdxyg000043j6jz458lguf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltmdxyg000053j6joq56rcy2%2522%252C%2522activeTabId%2522%253A%2522cltmdxyg000043j6jz458lguf%2522%257D%252C%2522cltmdxyg000033j6jnt6fvu7p%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltmdxyg000033j6jnt6fvu7p%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

I think this change does not require a new API, keep it simple, then this is my implementation suggestion

```typescript
import { ZodRawShape } from "zod";
import { RuleRender } from "rc-field-form/lib/interface";
import { AntdFormZodSchema } from "../types";
import validateFields from "./validateFields";
import prepareValues from "./prepareValues";

interface CreateSchemaFieldRuleOptions {
  ignorePrefix?: boolean;
}

const createSchemaFieldRule =
  <T extends ZodRawShape>(schema: AntdFormZodSchema<T>, options: CreateSchemaFieldRuleOptions = {}): RuleRender =>
    ({ getFieldsValue }) => ({
      validator: (rule) =>
        new Promise(async (resolve, reject) => {
          // AsyncValidator adds field - rc-field-form type isn't correct
          // https://github.com/search?q=repo%3Ayiminghe%2Fasync-validator%20fullField&type=code
          let { field } = rule as { field: string };
          if (options.ignorePrefix) {
            const indexOf = field.indexOf(".");
            if (indexOf !== -1) {
              field = field.slice(indexOf + 1);
            }
          }
          const values = getFieldsValue();
          const errors = await validateFields<T>(
            schema,
            prepareValues(schema, values),
          );

          if (!!errors && errors[field]) {
            reject(errors[field]);
            return;
          }

          resolve(undefined);
        }),
    });

export default createSchemaFieldRule;
```

**Comment by sia-fl** [comment]
If this idea is ok, then please review the pr #10

**Comment by MrBr** [comment]
If I understood correctly the antd pro table adds a prefix to `field` property in validator (being a row identifier) but expects error path to be without the prefix? This doesn't seem right, maybe there's something more.

There are some specifics when it comes to the list validation in the normal `Form`. For example, the input list must be wrapped with `Form.Item` in order for the validation to work properly, see it here https://github.com/MrBr/antd-zod/blob/main/stories/basic.stories.tsx#L102

Can you double check if this is really the case?

**Comment by sia-fl** [comment]
Ok, after get off work I will further think and test based on the use cases you provided.

**Comment by sia-fl** [comment]
Work was too heavy yesterday. I have tested it. First of all, it works through `Form.List`. My colleagues have switched many components that use `edit table` to `Form.List` and now they work normally.  

![image](https://github.com/MrBr/antd-zod/assets/39842393/1580073b-a6e2-4baa-bc0e-82246db08755)

However, the `edit table` of `pro component` has some special features. It uses the id of the same level as the prefix of the key. This PR only responds to this emergency situation. Now we should have three processing methods. 
- 1 Abandon compatibility
- 2 Merge pr 
- 3 Add new api

**Comment by sia-fl** [comment]
Maybe `Form.List` and potentially `edit table` should provide use cases in `readme.md`, which would help to reassure potential users

**Comment by MrBr** [comment]
In this case, if pro components require some specific behaviour I'd like to create a new function for it. something like `createSchemaProFieldRule` or `createSchemaProTableRule`. 

This will leave the old API as is and provide a new functionality without the special case.

Possibly you can use `createSchemaFieldRule` under the hood.
